### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by tianhaoz95** [tianhaoz95/flutter-pub-updater#1]
it shoud:
- [ ] takes a path to the root of a flutter project (default to proj root)
- [ ] takes a branch to send PR to (default to master)
- [ ] run pub update in the flutter project
- [ ] open a pull request to the desirable branch
